project/backend/models/product.py
# project/models/product.py
from ..config.database import db

class Product(db.Model):
    __tablename__ = 'Product'
    ProductId = db.Column(db.Integer, primary_key=True, autoincrement=True)
    Name = db.Column(db.Text)
    Description = db.Column(db.Text)
    Image = db.Column(db.Text)
    Price = db.Column(db.Float)
    Stock = db.Column(db.Integer)

project/backend/routes/accountPage.py
# backend/auth/accountPage.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from project.backend.auth.login import Login
from project.backend.auth.signup import Signup
import secrets

account_blueprint = Blueprint('account', __name__)

@account_blueprint.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'POST':
        login_data = Login(username=request.form['username'], password=request.form['password'])
        if login_data.authenticate() == True:
            session['username'] = request.form['username']
            # Generate token session
            session['user_token'] = secrets.token_urlsafe(16)
            flash('Login successful', 'success')
            return redirect(url_for('cart.render_user_pannel'))
        else:
            flash('Nom d\'utilisateur ou mot de passe incorrect', 'error')
    return render_template('login.html')

@account_blueprint.route('/register', methods=['POST', 'GET'])
def register():
    errors = {}
    if request.method == 'POST':
        signup_data = Signup(
            username=request.form['newUsername'],
            email=request.form['newEmail'],
            password=request.form['newPassword']
        )

        email_error = signup_data.invalid_mail()
        password_errors = signup_data.invalid_password()
        username_errors = signup_data.invalid_username()

        if email_error:
            errors['email'] = email_error
        if password_errors:
            errors['password'] = password_errors
        if username_errors:
            errors['username'] = username_errors

        if not errors:
            signup_data.create_account()
            flash('Compte créé avec succès', 'success')  
            return redirect(url_for('account.login'))  

    return render_template('register.html', errors=errors)


@account_blueprint.route('/logout', methods=['POST', 'GET'])
def logout():
    session.pop("username", None)
    flash('Vous avez été déconnecté', 'success')
    response = redirect(url_for('account.login')) 

    return response

project/backend/routes/payementPage.py
# project/routes/order_blueprint.py
from flask import Blueprint, render_template, request, redirect,  url_for, flash
from ..models.product import Product
from ..models.user import User
from ..utils.userGestion import UserManagement  
from ..utils.orderGestion import UserOrder

order_blueprint = Blueprint('order', __name__)
user_management = UserManagement()  

@order_blueprint.route('/order_summary', methods=['GET', 'POST'])
def get_order_summary():
    product_id = request.args.get('product_id')
    quantity = int(request.args.get('quantity', 1))
    username, user = user_management.get_user_info()
    product = Product.query.get(product_id)
    total_cost= product.Price * quantity

    if total_cost > user.Money :
        return render_template('payement.html', product=product, quantity=quantity, error=True )
    return render_template('payement.html', product=product, quantity=quantity)


@order_blueprint.route('/payment_process', methods=['GET','POST'])
def payment_process():
    product_id = request.form['product_id']  
    quantity = int(request.form['quantity'])
    username, user = user_management.get_user_info()
    if user == False or user is None  :
        return redirect('auth.login')

    newOrder = UserOrder(user.UserId, product_id)
    success, error_message, product = newOrder.add_product_to_order(quantity)
    
    if success:
        # flash("Le produit a été ajouté à votre commande avec succès.", "success")
        return redirect(url_for('cart.render_user_pannel'))
    # else:
    #     flash(error_message, "error")
    
    return redirect(url_for('cart.render_user_pannel'))

project/backend/routes/productsPage.py
from flask import Blueprint, render_template, flash, session, request, redirect, url_for
from ..utils.cartGestion import CartManagement
from ..utils.userGestion import UserManagement
from ..models.product import Product
from ..models.cart import Cart

products_blueprint = Blueprint('products', __name__)
user_management = UserManagement()

@products_blueprint.route('/', methods=['GET', 'POST'])
def render_product_page():
    products = Product.query.all()  
    username, user = user_management.get_user_info()
    for product in products:
        if product.Stock > 10:
            product.stock_status = 'En Stock'
        elif 0 < product.Stock <= 10:
            product.stock_status = f'Il reste {product.Stock} produit(s)'
        else:
            product.stock_status = 'Indisponible'
        notification = session.pop('notification', None)
    if user : 
        return render_template('products.html', products=products, connected=bool(user), notification=notification)
    else :
        return render_template('products.html', products=products, connected=bool(user), notification=notification)
    

@products_blueprint.route('/<int:product_id>', methods=['GET'])
def product_detail(product_id):
    product = Product.query.get(product_id)
    username, user = user_management.get_user_info()
    notification = session.pop('notification', None)
    if product.Stock > 10:
        stock_status = 'En stock'
    elif 0 < product.Stock <= 10:
        stock_status = f'Il reste {product.Stock} produit(s)'
    else:
        stock_status = 'Indisponible'
        return render_template('product_detail_sold_out.html', product=product, product_id=product_id, stock_status=stock_status, connected=bool(user), notification=notification)
    if user :
        return render_template('product_detail.html', product=product, product_id=product_id, stock_status=stock_status, connected=bool(user), notification=notification)
    else :
        return render_template('product_detail.html', product=product, product_id=product_id, stock_status=stock_status, connected=bool(user), notification=notification)
        

@products_blueprint.route('/add_item_to_cart', methods=['POST'])
def add_item_to_cart():
    username, user = user_management.get_user_info()
    if user:
        cart_manager = CartManagement(user.UserId)
        product_id = request.form.get('product_id')
        quantity = int(request.form.get('quantity', 1))
        cart_manager.add_item_to_cart(product_id, quantity)
        return redirect(url_for('cart.render_user_pannel', product_id=product_id))
    else:
        return redirect(url_for('account.login'))
    

@products_blueprint.route('/purchase_item', methods=['POST'])
def purchase():
    username, user = user_management.get_user_info()
    if user:
        product_id = request.form.get('product_id')
        quantity = int(request.form.get('quantity', 1))
        product = Product.query.get(product_id)
        return redirect(url_for('order.get_order_summary', product_id=product_id, quantity=quantity)) 
    else:
        return redirect(url_for('account.login'))

project/backend/routes/userPannel.py
# project/routes/cart_blueprint.py
from flask import Blueprint, render_template, redirect, url_for, flash, session, request
from ..models.order import Order
from ..models.product import Product
from ..config.database import db
from ..utils.cartGestion import CartManagement
from ..utils.userGestion import UserManagement  
from ..utils.orderGestion import UserOrder
from sqlalchemy import desc
from flask import jsonify

cart_blueprint = Blueprint('cart', __name__)
user_management = UserManagement()  

@cart_blueprint.route('/userPannel', methods=['GET', 'POST'])
def render_user_pannel():
    username, user = user_management.get_user_info()
    if not user:
        return redirect(url_for('account.login'))
    money = user.Money
    cart_manager = CartManagement(user.UserId)
    user_cart = cart_manager.get_user_cart()
    cart_details = cart_manager.get_cart_details(user_cart)
    user_id = user.UserId
    user_orders = Order.query.filter(Order.UserId == user_id).order_by(desc(Order.OrderDate)).limit(8).all()
    
    orders_details = []
    for order in user_orders:
        product = Product.query.get(order.ProductId)
        if product:
            orders_details.append({
                'product_name': product.Name,
                'quantity': order.Quantity,
                'price': order.Quantity * product.Price,  
                'order_date': order.OrderDate,
                'stock': product.Stock
            })
    
    return render_template('userPannel.html', username=username, money=money, user_cart=cart_details, user_orders=orders_details)


@cart_blueprint.route('/remove_item', methods=['POST'])
def remove_item():
    username, user = user_management.get_user_info()
    if user:
        user_id = user.UserId
        product_id = request.form['product_id']
        print(product_id)
        cart_manager = CartManagement(user_id)
        cart_manager.remove_item_from_cart(product_id)
        # flash('Produit supprimé du panier', 'success')
        return redirect(url_for('cart.render_user_pannel'))
    else:
        flash("Utilisateur non trouvé", 'error')
        return redirect(url_for('login'))
    

@cart_blueprint.route('/load-more-orders', methods=['GET'])
def load_more_orders():
    offset = request.args.get('offset', type=int)
    user_id = user_management.get_user_id()
    user_orders = Order.query.filter(Order.UserId == user_id).order_by(desc(Order.OrderDate)).offset(offset).limit(8).all()
    orders_details = []
    for order in user_orders:
        product = Product.query.get(order.ProductId)
        if product:
            orders_details.append({
                'product_name': product.Name,
                'quantity': order.Quantity,
                'price': order.Quantity * product.Price,  
                'order_date': order.OrderDate
            })
    return jsonify(orders_details)

@cart_blueprint.route('/purchase_from_cart', methods=['POST'])
def purchase_from_cart():
    username, user = user_management.get_user_info()
    if user:
        user_id = user.UserId
        product_id = request.form['product_id']
        quantity = int(request.form['quantity'])
        newOrder = UserOrder(user.UserId, product_id)
        success, error_message, product = newOrder.add_product_to_order(quantity)

        if success :
            cart_manager = CartManagement(user_id)
            cart_manager.delete_item_from_cart(product_id, quantity)
            return redirect(url_for('cart.render_user_pannel'))
        return redirect(url_for('cart.render_user_pannel'))
            
    flash('utilisateur inexistant')
    return redirect(url_for('account.login'))

templates/connectNavBar.html
<nav>
    <h1><a href="">Parcoursup Project</a></h1>
    <div class="burger-menu" onclick="toggleMenu()"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(255, 255, 255, 1);transform: msFilter"><path d="M4 6h16v2H4zm0 5h16v2H4zm0 5h16v2H4z"></path></svg></div>
    <ul class="nav-links">
      <li class="link-1"><a href="{{url_for('products.render_product_page')}}">Produits</a></li>
      <li class="link-4"><a href="{{url_for('account.logout')}}">Se déconnecter</a></li>
      <li class="link-2"><a href="{{url_for('cart.render_user_pannel')}}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(255, 255, 255, 1);transform: msFilter"><path d="M12 2A10.13 10.13 0 0 0 2 12a10 10 0 0 0 4 7.92V20h.1a9.7 9.7 0 0 0 11.8 0h.1v-.08A10 10 0 0 0 22 12 10.13 10.13 0 0 0 12 2zM8.07 18.93A3 3 0 0 1 11 16.57h2a3 3 0 0 1 2.93 2.36 7.75 7.75 0 0 1-7.86 0zm9.54-1.29A5 5 0 0 0 13 14.57h-2a5 5 0 0 0-4.61 3.07A8 8 0 0 1 4 12a8.1 8.1 0 0 1 8-8 8.1 8.1 0 0 1 8 8 8 8 0 0 1-2.39 5.64z"></path><path d="M12 6a3.91 3.91 0 0 0-4 4 3.91 3.91 0 0 0 4 4 3.91 3.91 0 0 0 4-4 3.91 3.91 0 0 0-4-4zm0 6a1.91 1.91 0 0 1-2-2 1.91 1.91 0 0 1 2-2 1.91 1.91 0 0 1 2 2 1.91 1.91 0 0 1-2 2z"></path></svg></a></li>
      <li class="link-3"><a href="https://github.com/kyamaoff/Parcoursup-Project"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(255, 255, 255, 1);transform: msFilter"><path fill-rule="evenodd" clip-rule="evenodd" d="M12.026 2c-5.509 0-9.974 4.465-9.974 9.974 0 4.406 2.857 8.145 6.821 9.465.499.09.679-.217.679-.481 0-.237-.008-.865-.011-1.696-2.775.602-3.361-1.338-3.361-1.338-.452-1.152-1.107-1.459-1.107-1.459-.905-.619.069-.605.069-.605 1.002.07 1.527 1.028 1.527 1.028.89 1.524 2.336 1.084 2.902.829.091-.645.351-1.085.635-1.334-2.214-.251-4.542-1.107-4.542-4.93 0-1.087.389-1.979 1.024-2.675-.101-.253-.446-1.268.099-2.64 0 0 .837-.269 2.742 1.021a9.582 9.582 0 0 1 2.496-.336 9.554 9.554 0 0 1 2.496.336c1.906-1.291 2.742-1.021 2.742-1.021.545 1.372.203 2.387.099 2.64.64.696 1.024 1.587 1.024 2.675 0 3.833-2.33 4.675-4.552 4.922.355.308.675.916.675 1.846 0 1.334-.012 2.41-.012 2.737 0 .267.178.577.687.479C19.146 20.115 22 16.379 22 11.974 22 6.465 17.535 2 12.026 2z"></path></svg></a></li>
    </ul>
</nav>

<script>
    function toggleMenu() {
        let navLinks = document.querySelector('.nav-links');
        navLinks.classList.toggle('active');
    }
</script>

<style>
    
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap');
nav {
    font-family: 'Poppins', sans-serif;
    display: flex;
    width: 90vw;
    height: 70px;
    justify-content: space-between;
    align-items: center;
    margin-top: 20px;
}
nav .burger-menu {
    background: none;
    border: none;
    display: none;
}
nav .burger-menu:hover {
    cursor: pointer;
}
nav svg {
    width: 50px;
    height: 50px;
}
nav h1 a {
    font-size: 2.1em;
    font-weight:600 ;
}
nav a {
    color: white;
}
nav .nav-links {
    display: flex;
    width: 30%;
    align-items: center;
    justify-content: space-between;
}
nav .nav-links a {
    font-size: 1.2em;
}
.nav-links svg {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 45px;
    height: 45px;
    border-radius: 454px;
}

.nav-links svg:hover {
    background: #bfbfbf35;
    transition-duration: 0.5s;
}

.nav-links .link-4 a{
    color: rgb(255, 25, 25);
    font-weight: 600;
}
@media screen and (max-width:1600px) {
    nav .nav-links {
        width: 40%;
    }
}

@media screen and (max-width:1300px) {
    nav .nav-links {
        width: 50%;
    }
}

@media screen and (max-width:800px) {
    nav .burger-menu {
        display: block;
        z-index: 56555;
    }
    nav .nav-links {
        flex-direction: column;
        position:fixed;
        top: 0;
        right: 0;
        margin-right: -50vw;
        width: 50vw;
        height: 100vh;
        padding: 30vh 0 30vh 0;
        box-sizing: border-box;
        background: #040404a0;
        backdrop-filter: blur(10px); 
        z-index: 56445;
        transition: all 0.5s ease-in-out;
    }
    nav .nav-links.active {
        margin-right: 0;
        }
}


</style>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World</title>
</head>
<body>
    <header>
        <nav>
            <h1><a href="">Ecom Parcoursup</a></h1>
            <ul class="navigation-link">
                <li class="link-1"><a href="">Acceuil</a></li>
                <li class="link-2"><a href="">Pannel Admin</a></li>
                <li class="link-3"><a href="">Documentation</a></li>
                <li class="link-4"><a href="">Connexion</a></li>
                <li class="link-5"><a href="">Créer un compte</a></li>
            </ul>
        </nav>
    </header>
    <main>
        section
    </main>
</body>
</html>

templates/navbar.html
<nav>
  <h1><a href="">Parcoursup Project</a></h1>
  <div class="burger-menu" onclick="toggleMenu()"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(255, 255, 255, 1);transform: msFilter"><path d="M4 6h16v2H4zm0 5h16v2H4zm0 5h16v2H4z"></path></svg></div>

  <ul class="nav-links">
    <li class="link-1"><a href="{{url_for('products.render_product_page')}}">Produits</a></li>
    <li class="link-2"><a href="{{url_for('account.login')}}">Se connecter</a></li>
    <li class="link-3"><a href="{{url_for('account.register')}}">S'inscrire</a></li>
    <li class="link-4"><a href="https://github.com/kyamaoff/Parcoursup-Project"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(255, 255, 255, 1);transform: msFilter"><path fill-rule="evenodd" clip-rule="evenodd" d="M12.026 2c-5.509 0-9.974 4.465-9.974 9.974 0 4.406 2.857 8.145 6.821 9.465.499.09.679-.217.679-.481 0-.237-.008-.865-.011-1.696-2.775.602-3.361-1.338-3.361-1.338-.452-1.152-1.107-1.459-1.107-1.459-.905-.619.069-.605.069-.605 1.002.07 1.527 1.028 1.527 1.028.89 1.524 2.336 1.084 2.902.829.091-.645.351-1.085.635-1.334-2.214-.251-4.542-1.107-4.542-4.93 0-1.087.389-1.979 1.024-2.675-.101-.253-.446-1.268.099-2.64 0 0 .837-.269 2.742 1.021a9.582 9.582 0 0 1 2.496-.336 9.554 9.554 0 0 1 2.496.336c1.906-1.291 2.742-1.021 2.742-1.021.545 1.372.203 2.387.099 2.64.64.696 1.024 1.587 1.024 2.675 0 3.833-2.33 4.675-4.552 4.922.355.308.675.916.675 1.846 0 1.334-.012 2.41-.012 2.737 0 .267.178.577.687.479C19.146 20.115 22 16.379 22 11.974 22 6.465 17.535 2 12.026 2z"></path></svg></a></li>
  </ul>
</nav>
<script>
    function toggleMenu() {
        let navLinks = document.querySelector('.nav-links');
        navLinks.classList.toggle('active');
    }
</script>
<style>
  
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap');
nav {
    font-family: 'Poppins', sans-serif;
    display: flex;
    width: 90vw;
    height: 70px;
    justify-content: space-between;
    align-items: center;
    margin-top: 20px;
}
nav .burger-menu {
    background: none;
    border: none;
    display: none;
}
nav .burger-menu:hover {
    cursor: pointer;
}
nav svg {
    width: 50px;
    height: 50px;
}
nav h1 a {
    font-size: 2.1em;
    font-weight:600 ;
}
nav a {
    color: white;
}
nav .nav-links {
    display: flex;
    width: 30%;
    align-items: center;
    justify-content: space-between;
}
nav .nav-links a {
    font-size: 1.2em;
}
.nav-links .link-2, .link-3 {
    border-radius: 0.3em;
    padding: 10px 15px 10px 15px;
    background: beige;
    font-size: 1em;
}
.nav-links .link-2 {
    background: rgb(115,18,218);
    background: linear-gradient(140deg, rgba(115,18,218,1) 0%, rgba(0,64,158,1) 100%);
}
.nav-links .link-2:hover {
    background: rgb(115,18,218);
    background: linear-gradient(140deg, rgba(115,18,218,.7) 0%, rgba(0,64,158,.7) 100%);
}

.nav-links .link-3 {
    background: rgb(255,85,23);
    transition: 0.3s;
    background: linear-gradient(140deg, rgba(255,85,23,1) 0%, rgba(222,154,17,1) 100%);
}
.nav-links .link-3:hover {
    background: rgb(255,85,23);
    background: linear-gradient(140deg, rgba(255,85,23,.7) 0%, rgba(222,154,17,.7) 100%);
    transition: 0.3s;
}
.nav-links svg {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 45px;
    height: 45px;
    border-radius: 454px;
}

.nav-links svg:hover {
    background: #bfbfbf35;
    transition-duration: 0.5s;
}
@media screen and (max-width:1600px) {
    nav .nav-links {
        width: 40%;
    }
}

@media screen and (max-width:1300px) {
    nav .nav-links {
        width: 50%;
    }
}

@media screen and (max-width:800px) {
    nav .burger-menu {
        display: block;
        z-index: 56555;
    }
    nav .nav-links {
        flex-direction: column;
        position:fixed;
        top: 0;
        right: 0;
        margin-right: -50vw;
        width: 50vw;
        height: 100vh;
        padding: 30vh 0 30vh 0;
        box-sizing: border-box;
        background: #040404a0;
        backdrop-filter: blur(10px); 
        z-index: 56445;
        transition: all 0.5s ease-out;
    }
    nav .nav-links.active {
        margin-right: 0;
        }
}
</style>

templates/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Angkor&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/product_details.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/navbar.css')}}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <title>Product page</title>
</head>
<body>
    {% if connected %}
        {% include 'connectNavBar.html' %}
    {% else %}
        {% include 'navbar.html' %}
    {% endif %}
    {% block content %}
    <main>
        <img class="block-left" src="{{product.Image}}" alt="{{product.Name}}">
        <div class="block-right">
            <div class="component-top">
                <h2>{{product.Name}}</h2>
                <span class="price-stock">
                    <p>◘ {{product.Price}} $</p>
                    <p>{{stock_status}}</p>
                </span>
            </div>
                <p class="description">
                    {{product.Description}}
                </p>
            <div class="redirect-buttons">
                <form id="productForm" method="post" action="{{ url_for('products.add_item_to_cart', product_id=product.ProductId) }}">
                    <input type="hidden" name="product_id" value="{{ product.ProductId }}">
                    <span class="input-wrapper">
                        <button type="button" id="decrement">-</button>
                        <input name='quantity' type="number" value="1" id="quantity" min='1' max='99' />
                        <button type="button" id="increment">+</button>
                    </span>
                    <button class='add_cart_button' type="submit">Ajouter au panier</button>
                    <button class='pay_button' type="submit" formaction="{{ url_for('products.purchase', product_id=product.ProductId) }}">Acheter maintenant</button>
                    <style>
                        button {
                            background: rgba(79, 79, 79, 0.543);
                        }
                        button:hover {
                            background: rgba(79, 79, 79, 0.543);
                        }
                    </style>
                </form>
            </div>
        </div>
    </main>

    {% endblock content%}
    <script>
         const quantityInput = document.querySelector("#quantity");

        document.getElementById('quantity').addEventListener('input', function() {
            quantityInput.value = this.value;
        });

        const incrementButton = document.querySelector("#increment");
        const decrementButton = document.querySelector("#decrement");

        incrementButton.addEventListener("click", () => {
            quantityInput.value = parseInt(quantityInput.value) + 1;
        });

        decrementButton.addEventListener("click", () => {
            // Vérifiez si la valeur est supérieure à 1 pour éviter les valeurs négatives
            if (parseInt(quantityInput.value) > 1) {
                quantityInput.value = parseInt(quantityInput.value) - 1;
            }
        });
    
    </script>

</body>
</html>

templates/userPannel.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Parcoursup Project | Utilisateur</title>
  <link rel="stylesheet" href="{{url_for('static', filename='css/user.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/reset.css')}}">  
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Madimi+One&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

</head>
<body>
    {% include 'connectNavBar.html'%}
  <main>
    <section class="account-gestion">
      <div class="container-component-account">
        <h2>Bonjour, {{username}}</h2>
        <span class="money-container">
          {{money}} $ 
        </span>
      </div>
    </section>
    <!-- <div class="shadow-effect-line">
      
    </div> -->
    <section class="bottom-container">
      <section class="cart-gestion-container">
        <h4>Panier</h4>
        <div class="product-gallery">
          {% for item in user_cart %}
          <div class="product">
            <div class="product-image">
              <form method="post" action="{{ url_for('cart.remove_item') }}">
                <input type="hidden" name="product_id" value="{{ item.product_id }}">
                <button class="delete-btn" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(255, 255, 255, 1);transform: msFilter"><path d="M5 20a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8h2V6h-4V4a2 2 0 0 0-2-2H9a2 2 0 0 0-2 2v2H3v2h2zM9 4h6v2H9zM8 8h9v12H7V8z"></path><path d="M9 10h2v8H9zm4 0h2v8h-2z"></path></svg></button>
              </form>
              <img src="{{ item.product_image }}" alt="{{ item.product_name }}">  
            </div>
            <div class="bottom-container-card">
              <div class="product-name">
                <h3>{{ item.product_name }}</h3>
              </div>
              <span class="price-quantity-container">
                <div class="product-price">
                  <p>{{ item.product_price*item.quantity }} $ </p>
                </div>
                <div class="product-quantity">
                  <p>Quantité : {{ item.quantity }}</p>
                </div>
              </span>
              <div class="stock">
                <p>{{item.stock_status}}</p>
              </div>
              <div class="product-actions">
                {% if item.product_price*item.quantity < money %}
                  <form method='post' action="{{url_for('cart.purchase_from_cart')}}">
                    <input type="hidden" name="product_id" value="{{item.product_id}}">
                    <input type="hidden" name="quantity" value="{{item.quantity}}">
                    <button class='buy-btn'type="submit">Acheter</button>
                  </form>
                {% elif item.product_quantity < item.quantity%}
                    <div class="stock-error">Stock insuffisant</div>
                {% else %}
                    <div class="sold-error">Solde insuffisant</div>
                {% endif %}
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </section>
      <section class="order-gestion-container">
        <div class="order-history">
          <h4>Commandes</h4>
            {% for order in user_orders %}
            <div class="orders-gallery"></div>
                <div class="order">
                  <span class="first-line">
                    <p>{{ order.product_name }}</p>
                  </span>
                  <span class="second-line">
                    <p>{{order.price}} $</p>
                    <p class="datetime">{{ order.order_date }}</p>
                  </span>
                </div>
            {% endfor %}
        </div>
      </section>
    </section>
  </main>
  <script src="{{ url_for('static', filename='js/user.js')}}"></script>
</body>
</html>